### ISSUE TITLE
Improper licensing and potential code theft

### ISSUE THREAD

**Issue by Mystifi** [HiTechFlufi/Tesla#1]
This is literally a rip off of sirDonovan's Cassius repository with the header comments removed, the README modified, and the license changed (which I'm pretty sure goes against the terms of the MIT License). As a contributor to the aforementioned repository, it's aggravating to see code stolen and passed off as original.

**Comment by HiTechFlufi** [comment]
I see where you're coming from, but I'm not really "ripping him off", I was using his bot as a base to get my own rolling. I planned to edit afterwards, all I'm doing right now is copying the files over so I can edit them. It's too early for people to judge anything.

**Comment by Mystifi** [comment]
Alright, I just wanted to see code properly attributed, both for the integrity (in respecting sirDonovan's code) and to avoid licensing conflicts. If all else fails, you can probably sublicense and label the files "LICENSE-MIT" and the other. I am sorry for being rude and harsh. Thank you for being compliant and kind.
